language: Rust
cache: cargo
sudo: false
rust:
- nightly
- beta
- stable
before_script:
- |
  pip install 'travis-cargo<0.2' --user &&
  export PATH=$HOME/.local/bin:$PATH
script:
- |
  travis-cargo --only nightly test -- --features nightly --no-default-features &&
  travis-cargo --only beta test &&
  travis-cargo --only stable test

env:
  global:
  - TRAVIS_CARGO_NIGHTLY_FEATURE="nightly"
