[package]
name = "gluon_language-server"
version = "0.1.1"
authors = ["Markus Westerlind <marwes91@gmail.com>"]
build = "build.rs"
description = "Language server providing completion for gluon"
license = "MIT"
repository = "https://github.com/Marwes/gluon_language-server"

[build-dependencies.serde_codegen]
version = "0.7.9"
optional = true

[dependencies.jsonrpc-core]
version = "2.0.7"
default-features = false

[dependencies]
log = "0.3.6"
env_logger = "0.3.3"
url = "1.2.0"

serde = "0.7.9"
serde_json = "0.7.1"

[dependencies.serde_macros]
version = "0.7.9"
optional = true

[dependencies.gluon]
version = "0.1.3"
default-features = false

[features]
default = ["serde_codegen", "jsonrpc-core/default"]
nightly = ["serde_macros", "jsonrpc-core/nightly"]