[package]
name = "gluon_language-server"
version = "0.1.1"
authors = ["Markus Westerlind <marwes91@gmail.com>"]
description = "Language server providing completion for gluon"
license = "MIT"
repository = "https://github.com/Marwes/gluon_language-server"

[workspace]

[dependencies]
log = "0.3.6"
env_logger = "0.3.3"
url = "1.2.0"

jsonrpc-core = { version = "3.0.0",  default-features = false }

serde = "0.8.11"
serde_json = "0.8.0"

[dependencies.vscode-languageserver-types]
path = "vscode-languageserver-types"
version = "0.1.0"
default-features = false

[dependencies.gluon]
git = "https://github.com/Marwes/gluon"
branch = "languageserver"
version = "0.2.0"
default-features = false

[features]
default = ["jsonrpc-core/default", "vscode-languageserver-types/default"]
nightly = ["jsonrpc-core/nightly", "vscode-languageserver-types/nightly"]
